# Generated by Django 3.2 on 2025-03-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='User ID associated with the token.', max_length=255)),
                ('service', models.CharField(help_text='The external service this token belongs to., e.g google, zoho.', max_length=50)),
                ('access_token', models.TextField(help_text='Access token for API authentication.')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token for obtaining a new access token.', null=True)),
                ('expires_at', models.DateTimeField(help_text='Expiration time of the access token.')),
                ('token_type', models.CharField(default='Bearer', help_text='Type of token (e.g., Bearer).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the token was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the token was last updated.')),
            ],
            options={
                'verbose_name': 'OAuth Token',
                'verbose_name_plural': 'OAuth Tokens',
            },
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['service', 'expires_at'], name='oauth_oauth_service_88b673_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oauthtoken',
            unique_together={('user_id', 'service')},
        ),
    ]
